# Generated by Django 5.2.6 on 2026-08-18 21:57

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import djangocms_frontend.fields
import filer.fields.image
import fragdenstaat_at.fds_mailing.models
import fragdenstaat_at.fds_mailing.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cms", "0045_pageurl_site_unique_path"),
        ("flowcontrol", "0007_alter_flowrun_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConditionCMSPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "context_key",
                    models.CharField(
                        help_text="Key to check in the context.", max_length=255
                    ),
                ),
                (
                    "context_value",
                    models.CharField(
                        blank=True,
                        help_text="Optional value to check on key. Checks for presence if empty.",
                        max_length=255,
                    ),
                ),
                (
                    "negate",
                    models.BooleanField(
                        default=False, help_text="Negate the condition."
                    ),
                ),
            ],
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="DelayMailActionConfig",
            fields=[
                (
                    "flowaction_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="flowcontrol.flowaction",
                    ),
                ),
                (
                    "delay_days",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of days to wait between emails."
                    ),
                ),
                (
                    "max_delay_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Maximum number of days to wait between emails. 0 means no limit.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("flowcontrol.flowaction",),
        ),
        migrations.CreateModel(
            name="EmailActionCMSPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("heading", models.CharField(blank=True, max_length=255)),
                ("action_url", models.CharField(blank=True, max_length=255)),
                ("action_label", models.CharField(blank=True, max_length=255)),
            ],
            bases=(
                fragdenstaat_at.fds_mailing.models.VariableTemplateMixin,
                "cms.cmsplugin",
            ),
        ),
        migrations.CreateModel(
            name="EmailButtonCMSPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("action_url", models.CharField(blank=True, max_length=255)),
                ("action_label", models.CharField(blank=True, max_length=255)),
                (
                    "attributes",
                    djangocms_frontend.fields.AttributesField(
                        blank=True, default=dict, verbose_name="Attributes"
                    ),
                ),
            ],
            bases=(
                fragdenstaat_at.fds_mailing.models.VariableTemplateMixin,
                "cms.cmsplugin",
            ),
        ),
        migrations.CreateModel(
            name="EmailSectionCMSPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
            ],
            bases=(
                fragdenstaat_at.fds_mailing.models.VariableTemplateMixin,
                "cms.cmsplugin",
            ),
        ),
        migrations.CreateModel(
            name="EmailStoryCMSPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("heading", models.CharField(blank=True, max_length=255)),
                ("url", models.URLField(blank=True, max_length=255)),
                ("label", models.CharField(blank=True, max_length=255)),
            ],
            bases=(
                fragdenstaat_at.fds_mailing.models.VariableTemplateMixin,
                "cms.cmsplugin",
            ),
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("category", models.CharField(blank=True, max_length=30)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("preheader", models.CharField(blank=True, max_length=255)),
                ("text", models.TextField(blank=True)),
                (
                    "template",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Default template"),
                            ("newsletter", "Newsletter template"),
                            ("formal", "Formal email template"),
                            ("mjml", "MJML email template"),
                        ],
                        max_length=255,
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                ("mail_intent", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "email template",
                "verbose_name_plural": "email templates",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="HasReceivedMailingActionConfig",
            fields=[
                (
                    "flowaction_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="flowcontrol.flowaction",
                    ),
                ),
                (
                    "negate",
                    models.BooleanField(
                        default=False, help_text="Negate the condition."
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("flowcontrol.flowaction",),
        ),
        migrations.CreateModel(
            name="MailingMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("sent", models.DateTimeField(blank=True, null=True)),
                ("bounced", models.BooleanField(default=False)),
                ("message", models.TextField(blank=True)),
                (
                    "is_continuous",
                    models.BooleanField(
                        default=False,
                        help_text="This message is part of a continuous mailing that tracks transactional messages.",
                        verbose_name="is continuous",
                    ),
                ),
            ],
            options={
                "verbose_name": "mailing message",
                "verbose_name_plural": "mailing messages",
                "ordering": ("-sent",),
            },
        ),
        migrations.CreateModel(
            name="MailingMessageReference",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="NewsletterArchiveCMSPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "number_of_mailings",
                    models.PositiveIntegerField(
                        default=6,
                        help_text="0 means all the mailings. Should be divisible by 3.",
                        verbose_name="number of mailing",
                    ),
                ),
            ],
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="RawCodeCMSPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("code", models.TextField(blank=True)),
            ],
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="SendMailActionConfig",
            fields=[
                (
                    "flowaction_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="flowcontrol.flowaction",
                    ),
                ),
                (
                    "only_once",
                    models.BooleanField(
                        default=True,
                        help_text="Only send this email once to this contact.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("flowcontrol.flowaction",),
        ),
        migrations.CreateModel(
            name="EmailHeaderCMSPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("color", models.CharField(blank=True, max_length=10)),
                (
                    "image",
                    filer.fields.image.FilerImageField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.FILER_IMAGE_MODEL,
                        verbose_name="image",
                    ),
                ),
            ],
            bases=(
                fragdenstaat_at.fds_mailing.models.VariableTemplateMixin,
                "cms.cmsplugin",
            ),
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "is_continuous",
                    models.BooleanField(
                        default=False,
                        help_text="This mailing is a continuous mailing that tracks transactional messages.",
                        verbose_name="is continuous",
                    ),
                ),
                ("sender_name", models.CharField(max_length=255)),
                (
                    "sender_email",
                    models.EmailField(
                        default=fragdenstaat_at.fds_mailing.models.get_default_sender_email,
                        max_length=255,
                        validators=[
                            fragdenstaat_at.fds_mailing.validators.validate_sender_domain
                        ],
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "publish",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Publish in archive.",
                        verbose_name="publish",
                    ),
                ),
                (
                    "tracking",
                    models.BooleanField(
                        default=False,
                        help_text="Track opens and clicks.",
                        verbose_name="tracking",
                    ),
                ),
                ("ready", models.BooleanField(default=False, verbose_name="ready")),
                (
                    "submitted",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="submitted"
                    ),
                ),
                (
                    "sending_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="sending date"
                    ),
                ),
                (
                    "sent_date",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="sent date"
                    ),
                ),
                (
                    "sent",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="sent"
                    ),
                ),
                (
                    "sending",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="sending"
                    ),
                ),
                (
                    "open_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times the email was opened.",
                        verbose_name="open count",
                    ),
                ),
                ("open_log_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "creator_user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mailings_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "email_template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fds_mailing.emailtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "mailing",
                "verbose_name_plural": "mailings",
                "ordering": ("-created",),
            },
            managers=[
                ("all_mailings", django.db.models.manager.Manager()),
            ],
        ),
    ]
