# Generated by Django 5.2.6 on 2026-08-18 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("fds_donation", "0044_regulardonorsprogressbarcmsplugin_and_more"),
        ("fds_mailing", "0001_initial"),
        ("fds_newsletter", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="newsletter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fds_newsletter.newsletter",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="segments",
            field=models.ManyToManyField(blank=True, to="fds_newsletter.segment"),
        ),
        migrations.AddField(
            model_name="mailing",
            name="sender_user",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mailings_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hasreceivedmailingactionconfig",
            name="mailing",
            field=models.ForeignKey(
                help_text="Mailing to check.",
                on_delete=django.db.models.deletion.CASCADE,
                to="fds_mailing.mailing",
            ),
        ),
        migrations.CreateModel(
            name="ContinuousMailing",
            fields=[],
            options={
                "verbose_name": "continuous mailing",
                "verbose_name_plural": "continuous mailings",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("fds_mailing.mailing",),
        ),
        migrations.AddField(
            model_name="mailingmessage",
            name="donor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fds_donation.donor",
            ),
        ),
        migrations.AddField(
            model_name="mailingmessage",
            name="mailing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipients",
                to="fds_mailing.mailing",
            ),
        ),
        migrations.AddField(
            model_name="mailingmessage",
            name="subscriber",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fds_newsletter.subscriber",
            ),
        ),
        migrations.AddField(
            model_name="mailingmessage",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mailingmessagereference",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="mailingmessagereference",
            name="mailing_message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="fds_mailing.mailingmessage",
            ),
        ),
        migrations.AddField(
            model_name="newsletterarchivecmsplugin",
            name="newsletter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="fds_newsletter.newsletter",
            ),
        ),
        migrations.AddField(
            model_name="sendmailactionconfig",
            name="email_template",
            field=models.ForeignKey(
                help_text="Email template to use for this action.",
                on_delete=django.db.models.deletion.CASCADE,
                to="fds_mailing.emailtemplate",
            ),
        ),
        migrations.AddConstraint(
            model_name="mailing",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_continuous", True), ("ready", True)),
                fields=("email_template",),
                name="unique_continuous_mailing_emailtemplate",
            ),
        ),
        migrations.AddConstraint(
            model_name="mailingmessage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_continuous", False)),
                fields=("mailing", "email"),
                name="unique_mailing_email",
            ),
        ),
        migrations.AddConstraint(
            model_name="mailingmessage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("subscriber__isnull", False)),
                fields=("mailing", "subscriber"),
                name="unique_mailing_subscriber",
            ),
        ),
        migrations.AddConstraint(
            model_name="mailingmessage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_continuous", False), ("user__isnull", False)),
                fields=("mailing", "user"),
                name="unique_mailing_user",
            ),
        ),
        migrations.AddIndex(
            model_name="mailingmessagereference",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="fds_mailing_content_f514ca_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="mailingmessagereference",
            constraint=models.UniqueConstraint(
                fields=("mailing_message", "content_type"),
                name="unique_mailing_message_content_type",
            ),
        ),
    ]
