version: '3'

services:
  db:
    image: postgis/postgis:14-3.1
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
  elasticsearch:
    build: ./deps/elasticsearch/
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - elasticsearch-log:/var/log
  backend:
    build: .
    command: honcho -f Procfile.dev start
    volumes:
      - ./froide:/code/froide
      - ./frontend:/code/frontend
      - ./fragdenstaat_at:/code/fragdenstaat_at
    links:
      - db
      - elasticsearch
    environment:
      - DJANGO_SETTINGS_MODULE=fragdenstaat_at.settings.development
      - DJANGO_CONFIGURATION=Dev
      - DATABASE_URL=postgis://postgres@db/postgres
    ports:
      - "8000:8000"
      - "8080:8080" # live reload
    depends_on:
      - db
      - elasticsearch

volumes:
  postgres_data: {}
  elasticsearch-data: {}
  elasticsearch-log: {}
