FROM blacktop/elasticsearch:6.3

RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install -b http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-plugin-bundle/6.3.2.1/elasticsearch-plugin-bundle-6.3.2.1.zip
