FROM python:3.5

ENV PYTHONUNBUFFERED 1
ENV DJANGO_SETTINGS_MODULE fragdenstaat_at.settings.development
ENV DJANGO_CONFIGURATION Dev
ENV NODE_ENV development

RUN apt-get update -y && apt-get install -y build-essential binutils libproj-dev libpq-dev gdal-bin libgeos-dev libgeos-c1v5 python-gdal

RUN curl -sL https://deb.nodesource.com/setup_9.x | bash - && apt-get update -y && apt-get install -y nodejs

RUN mkdir -p /code/code

COPY requirements-dev.txt /code/code/
COPY requirements.txt /code/code/
RUN pip install -r /code/code/requirements-dev.txt

WORKDIR /code/code/
EXPOSE 8000
