[project]
name = "fragdenstaat-at"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp==3.10.5",
    "aiosignal==1.3.1",
    "alabaster==0.7.12",
    "amqp==5.2.0",
    "appnope==0.1.3",
    "asgiref>=3.8.1",
    "asttokens==2.2.1",
    "async-timeout==4.0.2",
    "attrs==24.2.0",
    "babel==2.11.0",
    "backcall==0.2.0",
    "beautifulsoup4==4.11.1",
    "billiard==4.2.1",
    "black==22.12.0",
    "bleach==5.0.1",
    "brotli==1.0.9",
    "celery==5.5.2",
    "certifi==2022.12.7",
    "cffi",
    "cfgv==3.3.1",
    "channels==4.2.2",
    "charset-normalizer==2.1.1",
    "click==8.1.7",
    "click-didyoumean==0.3.1",
    "click-plugins==1.1.1",
    "click-repl==0.3.0",
    "coreschema==0.0.4",
    "coverage==7.0.0",
    "cryptography==48.0.0",
    "cssselect2==0.8.0",
    "decorator==5.1.1",
    "deprecated==1.2.13",
    "deprecation==2.1.0",
    "distlib==0.3.6",
    "dj-database-url==1.2.0",
    "django==5.2.6",
    "django-admin-sortable2==2.1.4",
    "django-amenities",
    "django-appconf==1.0.5",
    "django-celery-beat==2.8.1",
    "django-celery-email==3.0.0",
    "django-classy-tags==4.0.0",
    "django-cms==5.0.2",
    "django-configurations==2.5.1",
    "django-contractor",
    "django-contrib-comments==2.2.0",
    "django-countries==7.5",
    "django-coverage-plugin==3.0.0",
    "django-crossdomainmedia==0.0.4",
    "django-debug-toolbar==4.4.6",
    "django-elasticsearch-dsl==8.0",
    "django-entangled==0.6.2",
    "django-filer==3.3.1",
    "django-filingcabinet",
    "django-filter==25.1",
    "django-floppyforms==1.9.0",
    "django-formtools==2.5.1",
    "django-fsm==2.8.1",
    "django-js-asset==2.0.0",
    "django-json-widget==1.1.1",
    "django-leaflet==0.32.0",
    "django-legal-advice-builder",
    "django-localflavor==3.1",
    "django-logentry-admin==1.1.0",
    "django-mfa3==1.0.0",
    "django-mptt==0.14.0",
    "django-oauth-toolkit>=3.0.1",
    "django-parler==2.3",
    "django-payments[stripe]==1.0.0",
    "django-phonenumber-field[phonenumberslite]==7.0.1",
    "django-polymorphic==4.1.0",
    "django-sekizai==4.0.0",
    "django-select2==8.0.0",
    "django-storages==1.14.6",
    "django-taggit==6.1.0",
    "django-timezone-field==7.0",
    "django-tinymce==3.5.0",
    "django-treebeard==5.0.2",
    "djangocms-admin-style==3.3.1",
    "djangocms-alias==2.0.4",
    "djangocms-attributes-field==4.0.0",
    "djangocms-frontend==2.1.3",
    "djangocms-icon==2.1.0",
    "djangocms-link==5.0.1",
    "djangocms-picture==4.1.1",
    "djangocms-text==0.9.1",
    "djangocms-text-ckeditor==5.1.1",
    "djangocms-transfer==2.0.0a0",
    "djangocms-versioning==2.3.1",
    "djangocms-video==3.1.0",
    "djangorestframework==3.16.0",
    "djangorestframework-csv==2.1.1",
    "djangorestframework-jsonp==1.0.2",
    "dnspython==2.2.1",
    "docopt==0.6.2",
    "docutils==0.19",
    "drf-spectacular==0.28.0",
    "easy-thumbnails==2.10.1",
    "elasticsearch==8.15.1",
    "elasticsearch-dsl==8.15.2",
    "enmerkar==0.7.1",
    "et-xmlfile==1.1.0",
    "exceptiongroup==1.0.4",
    "executing==1.2.0",
    "factory-boy==3.2.1",
    "faker==15.3.4",
    "fcdocs-annotate",
    "fdfgen==0.16.1",
    "feedgen==0.9.0",
    "fido2>=2.0,<3.0",
    "filelock==3.8.2",
    "flake8==6.0.0",
    "flake8-bugbear==22.12.6",
    "fonttools[woff]==4.38.0",
    "froide",
    "froide-campaign",
    "froide-payment",
    "frozenlist>=1.8.0",
    "future==0.18.2",
    "geocoder==1.38.1",
    "geographiclib==2.0",
    "geoip2==4.6.0",
    "geopy==2.3.0",
    "greenlet==3.2.4",
    "honcho==1.1.0",
    "html-text==0.5.2",
    "html5lib==1.1",
    "htmldocx==0.0.6",
    "icalendar==5.0.3",
    "identify==2.5.10",
    "idna==3.4",
    "imagesize==1.4.1",
    "inflection==0.5.1",
    "iniconfig==1.1.1",
    "ipdb==0.13.11",
    "ipython==8.7.0",
    "isort==5.11.3",
    "itypes==1.2.0",
    "jedi==0.18.2",
    "jinja2==3.1.2",
    "jsonschema==4.17.3",
    "jwcrypto==1.5.0",
    "kombu==5.5.3",
    "lxml>=6.1.1",
    "markdown>=3.7",
    "markupsafe==2.1.1",
    "matplotlib-inline==0.1.6",
    "maxminddb==2.2.0",
    "mccabe==0.7.0",
    "mock==4.0.3",
    "multidict==6.0.3",
    "mypy-extensions==0.4.3",
    "nodeenv==1.7.0",
    "num2words==0.5.12",
    "oauthlib==3.2.2",
    "openpyxl==3.0.10",
    "packaging==22.0",
    "pandas>=3.0.3",
    "parso==0.8.3",
    "pathspec==0.10.3",
    "pbr==5.11.0",
    "pexpect==4.8.0",
    "pgpy==0.6.0",
    "phonenumbers==8.13.2",
    "phonenumberslite==8.13.2",
    "pickleshare==0.7.5",
    "pikepdf==9.7.0",
    "pillow>=12.2.0",
    "platformdirs==2.6.0",
    "pluggy==1.0.0",
    "pre-commit==2.20.0",
    "prices==1.1.1",
    "prompt-toolkit==3.0.36",
    "psycopg2-binary==2.9.5",
    "ptyprocess==0.7.0",
    "pure-eval==0.2.2",
    "pyasn1==0.4.8",
    "pycodestyle==2.10.0",
    "pycparser==2.21",
    "pycryptodome==3.16.0",
    "pydyf==0.11.0",
    "pyee==9.0.4",
    "pyflakes==3.0.1",
    "pygments==2.13.0",
    "pygtail",
    "pyisemail==2.0.1",
    "pynacl==1.5.0",
    "pyopenssl",
    "pyotp==2.8.0",
    "pypdf2==2.12.1",
    "pyphen==0.13.2",
    "pyrsistent==0.19.2",
    "pytest==7.2.0",
    "pytest-base-url==2.0.0",
    "pytest-django==4.5.2",
    "pytest-factoryboy==2.5.1",
    "pytest-playwright==0.3.0",
    "python-crontab==3.2.0",
    "python-dateutil==2.9.0.post0",
    "python-docx==0.8.11",
    "python-magic==0.4.27",
    "python-mimeparse==1.6.0",
    "python-slugify==7.0.0",
    "python-stdnum==1.18",
    "pytz==2022.7",
    "pywatchman==1.4.1",
    "pyyaml==6.0.2",
    "qrcode==7.3.1",
    "ratelim==0.1.6",
    "reportlab==4.4.1",
    "requests==2.28.1",
    "sentry-sdk==2.29.1",
    "setuptools==74.1.2",
    "six==1.16.0",
    "snowballstemmer==2.2.0",
    "sortabletable",
    "soupsieve==2.3.2.post1",
    "sphinx==5.3.0",
    "sphinxcontrib-applehelp==1.0.2",
    "sphinxcontrib-devhelp==1.0.2",
    "sphinxcontrib-htmlhelp==2.0.0",
    "sphinxcontrib-jsmath==1.0.1",
    "sphinxcontrib-qthelp==1.0.3",
    "sphinxcontrib-serializinghtml==1.1.5",
    "sqlparse==0.4.3",
    "stack-data==0.6.2",
    "stripe==7.14.0",
    "svglib==1.5.1",
    "tblib==1.7.0",
    "text-unidecode==1.3",
    "time-machine==2.9.0",
    "tinycss2==1.4.0",
    "toml==0.10.2",
    "tomli==2.0.1",
    "traitlets==5.8.0",
    "typing-extensions==4.12.2",
    "tzdata==2025.2",
    "unicodecsv==0.14.1",
    "unidecode==1.1.2",
    "uritemplate==4.1.1",
    "urllib3==1.26.13",
    "vine==5.1.0",
    "virtualenv==20.17.1",
    "wand==0.6.10",
    "wcwidth==0.2.5",
    "weasyprint>=65.1",
    "webencodings==0.5.1",
    "websockets==10.4",
    "wrapt==1.14.1",
    "xlrd==2.0.1",
    "yarl>=1.24.2",
    "zopfli==0.2.2",
]

[tool.uv.sources]
django-amenities = { git = "https://github.com/okfde/django-amenities.git", rev = "main" }
django-contractor = { git = "https://github.com/stefanw/django-contractor.git", rev = "main" }
django-filingcabinet = { git = "https://github.com/okfde/django-filingcabinet.git", rev = "main" }
django-legal-advice-builder = { git = "https://github.com/fragdenstaat/django-legal-advice-builder.git", rev = "main" }
fcdocs-annotate = { git = "https://github.com/okfde/fcdocs-annotate.git", rev = "main" }
froide = { git = "https://github.com/okfde/froide.git", rev = "main" }
froide-campaign = { git = "https://github.com/okfde/froide-campaign.git", rev = "main" }
froide-payment = { git = "https://github.com/okfde/froide-payment.git", rev = "main" }
pygtail = { git = "https://github.com/okfde/pygtail.git", rev = "3be17b00f55781caba62d589bcf8aceb0805a58c" }
sortabletable = { git = "https://github.com/stefanw/djangocms-sortabletable.git", rev = "main" }
