# Generated by Django 5.2.17 on 2026-09-02 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cms", "0045_pageurl_site_unique_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="RSSFeedCache",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True, verbose_name="feed URL")),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="cached feed"
                    ),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last fetched"
                    ),
                ),
                ("etag", models.CharField(blank=True, max_length=512)),
                ("last_modified", models.CharField(blank=True, max_length=128)),
                ("error", models.TextField(blank=True, verbose_name="last error")),
            ],
            options={
                "verbose_name": "RSS feed cache",
                "verbose_name_plural": "RSS feed caches",
            },
        ),
        migrations.CreateModel(
            name="RSSFeedCMSPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("url", models.URLField(verbose_name="feed URL")),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to use the feed's own title.",
                        max_length=255,
                        verbose_name="heading",
                    ),
                ),
                (
                    "count",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="entries to show"
                    ),
                ),
                (
                    "show_summary",
                    models.BooleanField(default=True, verbose_name="show summary text"),
                ),
            ],
            bases=("cms.cmsplugin",),
        ),
    ]
