# Generated by Django 5.2.17 on 2026-09-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fds_cms_at", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rssfeedcmsplugin",
            name="show_title",
            field=models.BooleanField(default=True, verbose_name="show heading"),
        ),
    ]
