# Generated by Django 5.2.17 on 2026-09-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fds_cms_at", "0002_rssfeedcmsplugin_show_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="rssfeedcmsplugin",
            name="show_image",
            field=models.BooleanField(
                default=True,
                help_text="Shows the most recent entry's image above the heading if the feed provides one.",
                verbose_name="show image",
            ),
        ),
    ]
