# Generated by Django 4.1.4 on 2023-01-23 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import cms.models.fields
import djangocms_bootstrap4.fields
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        (
            "fds_cms",
            "0003_cardcmsplugin_cardheadercmsplugin_cardiconcmsplugin_cardimagecmsplugin_cardinnercmsplugin",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BorderedSectionCMSPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "border",
                    models.CharField(
                        choices=[
                            ("blue", "Blue"),
                            ("gray", "Gray"),
                            ("yellow", "Yellow"),
                        ],
                        default="gray",
                        max_length=50,
                        verbose_name="Border",
                    ),
                ),
                (
                    "spacing",
                    models.CharField(
                        choices=[("sm", "Small"), ("md", "Medium"), ("lg", "Large")],
                        default="md",
                        max_length=3,
                        verbose_name="Spacing",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        choices=[
                            ("h1", "Headline 1"),
                            ("h2", "Headline 2"),
                            ("h3", "Headline 3"),
                            ("h4", "Headline 4"),
                            ("h5", "Headline 5"),
                            ("h6", "Headline 6"),
                        ],
                        default="h3",
                        max_length=5,
                        verbose_name="Heading level",
                    ),
                ),
                (
                    "attributes",
                    djangocms_bootstrap4.fields.AttributesField(
                        blank=True, default=dict, verbose_name="Attributes"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="DropdownBannerCMSPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "animation",
                    models.BooleanField(
                        default=True, verbose_name="Slide banner with animation"
                    ),
                ),
                (
                    "dark",
                    models.BooleanField(
                        default=False,
                        verbose_name="Banner is dark-themed, button should therefore be light",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="RevealMoreCMSPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "cutoff",
                    models.PositiveIntegerField(default=1, verbose_name="Cutoff after"),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("rows", "grid rows"),
                            ("rem", "Line heights"),
                            ("%", "percent"),
                        ],
                        max_length=10,
                        verbose_name="Unit",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("", "None"),
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("info", "Info"),
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("danger", "Danger"),
                            ("purple", "Purple"),
                            ("pink", "Pink"),
                            ("yellow", "Yellow"),
                            ("cyan", "Cyan"),
                            ("gray", "Gray"),
                            ("gray-dark", "Gray Dark"),
                            ("white", "White"),
                            ("gray-100", "Gray 100"),
                            ("gray-200", "Gray 200"),
                            ("gray-300", "Gray 300"),
                            ("gray-400", "Gray 400"),
                            ("gray-500", "Gray 500"),
                            ("gray-600", "Gray 600"),
                            ("gray-700", "Gray 700"),
                            ("gray-800", "Gray 800"),
                            ("gray-900", "Gray 900"),
                            ("blue-10", "Blue 10"),
                            ("blue-20", "Blue 20"),
                            ("blue-30", "Blue 30"),
                            ("blue-100", "Blue 100"),
                            ("blue-200", "Blue 200"),
                            ("blue-300", "Blue 300"),
                            ("blue-400", "Blue 400"),
                            ("blue-500", "Blue 500"),
                            ("blue-600", "Blue 600"),
                            ("blue-700", "Blue 700"),
                            ("blue-800", "Blue 800"),
                            ("yellow-100", "Yellow 100"),
                            ("yellow-200", "Yellow 200"),
                            ("yellow-300", "Yellow 300"),
                        ],
                        max_length=50,
                        verbose_name="Overlay color",
                    ),
                ),
                (
                    "reveal_text",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Reveal text"
                    ),
                ),
                (
                    "attributes",
                    djangocms_bootstrap4.fields.AttributesField(
                        blank=True, default=dict, verbose_name="Attributes"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
        migrations.RemoveField(
            model_name="cardcmsplugin",
            name="extra_classes",
        ),
        migrations.RemoveField(
            model_name="cardheadercmsplugin",
            name="extra_classes",
        ),
        migrations.RemoveField(
            model_name="cardiconcmsplugin",
            name="extra_classes",
        ),
        migrations.RemoveField(
            model_name="cardiconcmsplugin",
            name="overlap",
        ),
        migrations.RemoveField(
            model_name="cardimagecmsplugin",
            name="extra_classes",
        ),
        migrations.RemoveField(
            model_name="cardinnercmsplugin",
            name="background",
        ),
        migrations.RemoveField(
            model_name="cardinnercmsplugin",
            name="extra_classes",
        ),
        migrations.RemoveField(
            model_name="designcontainercmsplugin",
            name="style",
        ),
        migrations.AddField(
            model_name="cardcmsplugin",
            name="attributes",
            field=djangocms_bootstrap4.fields.AttributesField(
                blank=True, default=dict, verbose_name="Attributes"
            ),
        ),
        migrations.AddField(
            model_name="cardcmsplugin",
            name="background",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("primary", "Primary"),
                    ("secondary", "Secondary"),
                    ("info", "Info"),
                    ("light", "Light"),
                    ("dark", "Dark"),
                    ("success", "Success"),
                    ("warning", "Warning"),
                    ("danger", "Danger"),
                    ("purple", "Purple"),
                    ("pink", "Pink"),
                    ("yellow", "Yellow"),
                    ("cyan", "Cyan"),
                    ("gray", "Gray"),
                    ("gray-dark", "Gray Dark"),
                    ("white", "White"),
                    ("gray-100", "Gray 100"),
                    ("gray-200", "Gray 200"),
                    ("gray-300", "Gray 300"),
                    ("gray-400", "Gray 400"),
                    ("gray-500", "Gray 500"),
                    ("gray-600", "Gray 600"),
                    ("gray-700", "Gray 700"),
                    ("gray-800", "Gray 800"),
                    ("gray-900", "Gray 900"),
                    ("blue-10", "Blue 10"),
                    ("blue-20", "Blue 20"),
                    ("blue-30", "Blue 30"),
                    ("blue-100", "Blue 100"),
                    ("blue-200", "Blue 200"),
                    ("blue-300", "Blue 300"),
                    ("blue-400", "Blue 400"),
                    ("blue-500", "Blue 500"),
                    ("blue-600", "Blue 600"),
                    ("blue-700", "Blue 700"),
                    ("blue-800", "Blue 800"),
                    ("yellow-100", "Yellow 100"),
                    ("yellow-200", "Yellow 200"),
                    ("yellow-300", "Yellow 300"),
                ],
                default="",
                max_length=50,
                verbose_name="Background",
            ),
        ),
        migrations.AddField(
            model_name="cardcmsplugin",
            name="page_link",
            field=cms.models.fields.PageField(
                blank=True,
                help_text="if present card will be clickable",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cms.page",
                verbose_name="page link",
            ),
        ),
        migrations.AddField(
            model_name="cardcmsplugin",
            name="url",
            field=models.CharField(
                blank=True,
                help_text="if present card will be clickable",
                max_length=255,
                null=True,
                verbose_name="link",
            ),
        ),
        migrations.AddField(
            model_name="cardheadercmsplugin",
            name="attributes",
            field=djangocms_bootstrap4.fields.AttributesField(
                blank=True, default=dict, verbose_name="Attributes"
            ),
        ),
        migrations.AddField(
            model_name="cardheadercmsplugin",
            name="background_image",
            field=filer.fields.image.FilerImageField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.FILER_IMAGE_MODEL,
                verbose_name="Background image",
            ),
        ),
        migrations.AddField(
            model_name="cardiconcmsplugin",
            name="attributes",
            field=djangocms_bootstrap4.fields.AttributesField(
                blank=True, default=dict, verbose_name="Attributes"
            ),
        ),
        migrations.AddField(
            model_name="cardimagecmsplugin",
            name="attributes",
            field=djangocms_bootstrap4.fields.AttributesField(
                blank=True, default=dict, verbose_name="Attributes"
            ),
        ),
        migrations.AddField(
            model_name="cardimagecmsplugin",
            name="page_link",
            field=cms.models.fields.PageField(
                blank=True,
                help_text="if present image will be clickable",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cms.page",
                verbose_name="page link",
            ),
        ),
        migrations.AddField(
            model_name="cardimagecmsplugin",
            name="size",
            field=models.CharField(
                choices=[("sm", "Small"), ("lg", "Large"), ("lg-wide", "Large (wide)")],
                default="lg",
                max_length=10,
                verbose_name="Size",
            ),
        ),
        migrations.AddField(
            model_name="cardimagecmsplugin",
            name="url",
            field=models.CharField(
                blank=True,
                help_text="if present image will be clickable",
                max_length=255,
                null=True,
                verbose_name="link",
            ),
        ),
        migrations.AddField(
            model_name="cardinnercmsplugin",
            name="attributes",
            field=djangocms_bootstrap4.fields.AttributesField(
                blank=True, default=dict, verbose_name="Attributes"
            ),
        ),
        migrations.AlterField(
            model_name="cardcmsplugin",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
        migrations.AlterField(
            model_name="cardcmsplugin",
            name="shadow",
            field=models.CharField(
                choices=[("no", "No"), ("auto", "Auto"), ("always", "Always")],
                default="no",
                max_length=10,
                verbose_name="Shadow",
            ),
        ),
        migrations.AlterField(
            model_name="cardcmsplugin",
            name="spacing",
            field=models.CharField(
                choices=[("sm", "Small"), ("md", "Medium"), ("lg", "Large")],
                default="md",
                max_length=3,
                verbose_name="Spacing",
            ),
        ),
        migrations.AlterField(
            model_name="cardheadercmsplugin",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
        migrations.AlterField(
            model_name="cardiconcmsplugin",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
        migrations.AlterField(
            model_name="cardimagecmsplugin",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
        migrations.AlterField(
            model_name="cardimagecmsplugin",
            name="overlap",
            field=models.CharField(
                choices=[("left", "Left"), ("right", "Right"), ("center", "Center")],
                default="right",
                max_length=10,
                verbose_name="Overlap",
            ),
        ),
        migrations.AlterField(
            model_name="cardinnercmsplugin",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
        migrations.AlterField(
            model_name="collapsiblecmsplugin",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
        migrations.AlterField(
            model_name="designcontainercmsplugin",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
        migrations.AlterField(
            model_name="documentcollectionembedcmsplugin",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
        migrations.AlterField(
            model_name="documentembedcmsplugin",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
        migrations.AlterField(
            model_name="documentpagescmsplugin",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
        migrations.AlterField(
            model_name="documentportalembedcmsplugin",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
        migrations.AlterField(
            model_name="foirequestlistcmsplugin",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
        migrations.AlterField(
            model_name="modalcmsplugin",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
        migrations.AlterField(
            model_name="oneclickfoirequestcmsplugin",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
        migrations.AlterField(
            model_name="pageannotationcmsplugin",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
        migrations.AlterField(
            model_name="primarylinkcmsplugin",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
        migrations.AlterField(
            model_name="sharelinkscmsplugin",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
        migrations.AlterField(
            model_name="slidercmsplugin",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
        migrations.AlterField(
            model_name="svgimagecmsplugin",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
        migrations.AlterField(
            model_name="vegachartcmsplugin",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
        migrations.AlterField(
            model_name="vegachartcmsplugin",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="CardLinkCMSPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "url",
                    models.CharField(blank=True, max_length=255, verbose_name="link"),
                ),
                ("arrow", models.BooleanField(default=False)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text='Enter an icon name from the <a href="https://fontawesome.com/v4.7.0/icons/" target="_blank">FontAwesome 4 icon set</a>',
                        max_length=50,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "attributes",
                    djangocms_bootstrap4.fields.AttributesField(
                        blank=True, default=dict, verbose_name="Attributes"
                    ),
                ),
                (
                    "page_link",
                    cms.models.fields.PageField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cms.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
    ]
