# Generated by Django 5.2.6 on 2026-07-06 21:53

import djangocms_frontend.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fds_cms", "0004_borderedsectioncmsplugin_dropdownbannercmsplugin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="borderedsectioncmsplugin",
            name="attributes",
            field=djangocms_frontend.fields.AttributesField(
                blank=True, default=dict, verbose_name="Attributes"
            ),
        ),
        migrations.AddField(
            model_name="cardcmsplugin",
            name="attributes",
            field=djangocms_frontend.fields.AttributesField(
                blank=True, default=dict, verbose_name="Attributes"
            ),
        ),
        migrations.AddField(
            model_name="cardheadercmsplugin",
            name="attributes",
            field=djangocms_frontend.fields.AttributesField(
                blank=True, default=dict, verbose_name="Attributes"
            ),
        ),
        migrations.AddField(
            model_name="cardiconcmsplugin",
            name="attributes",
            field=djangocms_frontend.fields.AttributesField(
                blank=True, default=dict, verbose_name="Attributes"
            ),
        ),
        migrations.AddField(
            model_name="cardimagecmsplugin",
            name="attributes",
            field=djangocms_frontend.fields.AttributesField(
                blank=True, default=dict, verbose_name="Attributes"
            ),
        ),
        migrations.AddField(
            model_name="cardinnercmsplugin",
            name="attributes",
            field=djangocms_frontend.fields.AttributesField(
                blank=True, default=dict, verbose_name="Attributes"
            ),
        ),
        migrations.AddField(
            model_name="cardlinkcmsplugin",
            name="attributes",
            field=djangocms_frontend.fields.AttributesField(
                blank=True, default=dict, verbose_name="Attributes"
            ),
        ),
        migrations.AddField(
            model_name="modalcmsplugin",
            name="attributes",
            field=djangocms_frontend.fields.AttributesField(
                blank=True, default=dict, verbose_name="Attributes"
            ),
        ),
        migrations.AddField(
            model_name="modalcmsplugin",
            name="dialog_attributes",
            field=djangocms_frontend.fields.AttributesField(
                blank=True, default=dict, verbose_name="Attributes"
            ),
        ),
        migrations.AddField(
            model_name="modalcmsplugin",
            name="tag_type",
            field=djangocms_frontend.fields.TagTypeField(
                default="div",
                help_text="Select the HTML tag to be used.",
                max_length=255,
                verbose_name="Tag type",
            ),
        ),
        migrations.AddField(
            model_name="revealmorecmsplugin",
            name="attributes",
            field=djangocms_frontend.fields.AttributesField(
                blank=True, default=dict, verbose_name="Attributes"
            ),
        ),
    ]
