# Generated by Django 5.2.6 on 2026-08-18 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fds_cms", "0006_static_placeholders_to_aliases"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fdspageextension",
            name="public_extension",
        ),
    ]
