services:
  web:
    build:
      context: ..
      dockerfile: fragdenstaat_at/.devcontainer/Dockerfile
    volumes:
     - type: bind
       source: $SSH_AUTH_SOCK
       target: /run/host-services/ssh-auth.sock
     - ..:/workspaces/fds_at:cached
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: fragdenstaat_at
      DATABASE_USER: fragdenstaat_at
      DATABASE_PASSWORD: fragdenstaat_at
      DJANGO_ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      DJANGO_SETTINGS_MODULE: fragdenstaat_at.settings.development
      DJANGO_CONFIGURATION: Dev
      SSH_AUTH_SOCK: /run/host-services/ssh-auth.sock
    init: true
    command: sleep infinity
    depends_on:
      - db
      - elasticsearch

  db:
    environment:
      POSTGRES_USER: fragdenstaat_at
      POSTGRES_DB: fragdenstaat_at
      POSTGRES_PASSWORD: fragdenstaat_at
volumes:
  pnpm_cache:
  uv_cache: