# Generated by Django 4.1.4 on 2023-02-12 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        ("fds_donation", "0043_remove_donation_received"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegularDonorsProgressBarCMSPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                (
                    "minimal_annual_contribution",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("white_text", models.BooleanField(default=False)),
                (
                    "regular_donors_goal",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
        migrations.AlterField(
            model_name="donation",
            name="project",
            field=models.CharField(
                choices=[("FOI", "Forum Informationsfreiheit")],
                default="FOI",
                max_length=40,
            ),
        ),
    ]
