# Generated by Django 5.2.6 on 2026-08-18 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fds_donation", "0044_regulardonorsprogressbarcmsplugin_and_more"),
        ("fds_newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="subscriber",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fds_newsletter.subscriber",
            ),
        ),
    ]
