# Generated by Django 5.2.6 on 2026-08-19 00:07

import decimal
import django.db.models.deletion
import django.utils.timezone
import djangocms_frontend.fields
import fragdenstaat_at.fds_donation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0045_pageurl_site_unique_path"),
        ("fds_donation", "0045_donor_subscriber"),
        ("flowcontrol", "0007_alter_flowrun_status"),
        ("froide_payment", "0020_subscription_cancel_trigger_subscription_canceled_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailDonationButtonCMSPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("once", "Only once"),
                            ("recurring", "Only recurring"),
                            ("once_recurring", "Both"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount_presets", models.CharField(blank=True, max_length=255)),
                ("initial_amount", models.IntegerField(blank=True, null=True)),
                ("initial_interval", models.IntegerField(blank=True, null=True)),
                ("min_amount", models.IntegerField(default=0)),
                ("prefilled_amount", models.BooleanField(default=True)),
                ("action_url", models.CharField(blank=True, max_length=255)),
                ("action_label", models.CharField(blank=True, max_length=255)),
                (
                    "attributes",
                    djangocms_frontend.fields.AttributesField(
                        blank=True, default=dict, verbose_name="Attributes"
                    ),
                ),
            ],
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="RecentlyDonatedActionConfig",
            fields=[
                (
                    "flowaction_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="flowcontrol.flowaction",
                    ),
                ),
                ("since_date", models.DateTimeField(blank=True, null=True)),
                ("since_days", models.PositiveSmallIntegerField(default=0)),
                (
                    "negate",
                    models.BooleanField(
                        default=False,
                        help_text="If hasn't recently donated",
                        verbose_name="Negate condition",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("flowcontrol.flowaction",),
        ),
        migrations.CreateModel(
            name="RemoteDonationFormCMSPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("remote_url", models.URLField()),
                ("title", models.CharField(blank=True, max_length=255)),
                ("show_title", models.BooleanField(default=True)),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("once", "Only once"),
                            ("recurring", "Only recurring"),
                            ("once_recurring", "Both"),
                        ],
                        max_length=20,
                    ),
                ),
                ("interval_choices", models.CharField(blank=True, max_length=255)),
                ("amount_presets", models.CharField(blank=True, max_length=255)),
                ("initial_amount", models.IntegerField(blank=True, null=True)),
                ("initial_interval", models.IntegerField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=255)),
                ("keyword", models.CharField(blank=True, max_length=255)),
                ("open_in_new_tab", models.BooleanField(default=True)),
            ],
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="UpgradeRecurrenceFormCMSPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("choice_count", models.SmallIntegerField(default=3)),
                ("days_since", models.IntegerField(default=0)),
                ("reference", models.CharField(blank=True, max_length=255)),
                ("next_url", models.CharField(blank=True, max_length=255)),
            ],
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="DeferredDonation",
            fields=[],
            options={
                "verbose_name": "Deferred Donation",
                "verbose_name_plural": "Deferred Donation",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("fds_donation.donation",),
        ),
        migrations.AlterModelOptions(
            name="donationgiftorder",
            options={
                "ordering": ("-timestamp",),
                "verbose_name": "donation gift order",
                "verbose_name_plural": "donation gift orders",
            },
        ),
        migrations.AddField(
            model_name="donation",
            name="data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="donation",
            name="extra_action_label",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="donation",
            name="extra_action_url",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="donation",
            name="form_url",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name="donationformcmsplugin",
            name="hide_account",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="donationformcmsplugin",
            name="hide_contact",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="donationformcmsplugin",
            name="interval_choices",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="donationformcmsplugin",
            name="next_label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="donationformcmsplugin",
            name="open_in_new_tab",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="donationformcmsplugin",
            name="payment_methods",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="donationformcmsplugin",
            name="quick_payment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No quick payment"),
                    ("show", "Show quick payment options"),
                    ("only", "Only quick payment options"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="donationgift",
            name="download_url",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="donationgift",
            name="gift_type",
            field=models.IntegerField(
                choices=[(1, "Physical"), (2, "Virtual")], default=1
            ),
        ),
        migrations.AddField(
            model_name="donationgift",
            name="inventory",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="donationgift",
            name="min_recurring_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="donationgift",
            name="min_streak_months",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="donationgiftorder",
            name="processing",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="donationprogressbarcmsplugin",
            name="initial_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=decimal.Decimal, max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="donationprogressbarcmsplugin",
            name="purpose",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="donor",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="donor",
            name="recurrence_streak_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="donation",
            name="keyword",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="donation",
            name="project",
            field=models.CharField(
                choices=fragdenstaat_at.fds_donation.models.get_project_choices,
                default="FOI",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="reference",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="donationformcmsplugin",
            name="next_url",
            field=models.CharField(
                blank=True,
                max_length=255,
                validators=[
                    fragdenstaat_at.fds_donation.models.validate_allowed_host_and_scheme
                ],
            ),
        ),
        migrations.AlterField(
            model_name="donor",
            name="become_user",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="donor",
            name="contact_allowed",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="donor",
            name="receipt",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.CreateModel(
            name="DonationFormViewCount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                ("reference", models.CharField(blank=True, max_length=255)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("count", models.PositiveBigIntegerField(default=0)),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Donation Form View Count",
                "verbose_name_plural": "Donation Form View Counts",
                "ordering": ("-last_updated",),
                "indexes": [
                    models.Index(
                        fields=["path", "reference", "date"],
                        name="fds_donatio_path_38930d_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("path", "reference", "date"), name="unique_path_ref"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DonorEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "kind",
                    models.CharField(
                        choices=fragdenstaat_at.fds_donation.models.get_donor_event_kinds,
                        max_length=255,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=255)),
                ("context", models.JSONField(default=dict)),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="fds_donation.donor",
                    ),
                ),
            ],
            options={
                "verbose_name": "donor event",
                "verbose_name_plural": "donor events",
            },
        ),
        migrations.CreateModel(
            name="DonorTagActionConfig",
            fields=[
                (
                    "flowaction_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="flowcontrol.flowaction",
                    ),
                ),
                (
                    "remove",
                    models.BooleanField(
                        default=False,
                        help_text="If checked will remove the tag from the donor instead of adding it.",
                        verbose_name="Remove tag",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fds_donation.donortag",
                        verbose_name="Donor Tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("flowcontrol.flowaction",),
        ),
        migrations.CreateModel(
            name="Recurrence",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "project",
                    models.CharField(
                        choices=fragdenstaat_at.fds_donation.models.get_project_choices,
                        default="FOI",
                        max_length=40,
                    ),
                ),
                ("method", models.CharField(blank=True, max_length=256)),
                ("start_date", models.DateTimeField()),
                (
                    "interval",
                    models.IntegerField(
                        choices=fragdenstaat_at.fds_donation.models.get_recurring_interval_choices
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("last_upgrade", models.DateTimeField(blank=True, null=True)),
                ("cancel_date", models.DateTimeField(blank=True, null=True)),
                (
                    "cancel_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "No reason given"),
                            ("financial", "Financial reasons"),
                            (
                                "unintended",
                                "Mistakenly set up, do not remember doing so",
                            ),
                            ("lost", "I do not want to support this project anymore"),
                            ("other", "Other"),
                        ],
                        default="",
                        help_text="Reason for cancellation",
                        max_length=255,
                    ),
                ),
                ("cancel_feedback", models.TextField(blank=True)),
                (
                    "donor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurrences",
                        to="fds_donation.donor",
                    ),
                ),
                (
                    "subscription",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="froide_payment.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurring donation",
                "verbose_name_plural": "Recurring donations",
            },
        ),
        migrations.AddField(
            model_name="donation",
            name="recurrence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="donations",
                to="fds_donation.recurrence",
            ),
        ),
    ]
