# Generated by Django 5.2.6 on 2026-08-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fds_donation", "0046_emaildonationbuttoncmsplugin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationformcmsplugin",
            name="hide_receipt",
            field=models.BooleanField(default=False),
        ),
    ]
