# Generated by Django 5.2.6 on 2026-08-18 21:57

import django.db.models.deletion
import django.utils.timezone
import fragdenstaat_at.fds_newsletter.models
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cms", "0045_pageurl_site_unique_path"),
        ("fds_mailing", "0001_initial"),
        ("flowcontrol", "0007_alter_flowrun_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                ("description", models.TextField(blank=True)),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "negate",
                    models.BooleanField(default=False, verbose_name="negate tags"),
                ),
                ("archived", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "segment",
                "verbose_name_plural": "segments",
            },
        ),
        migrations.CreateModel(
            name="SubscriberTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=100,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscriber Tag",
                "verbose_name_plural": "Subscriber Tags",
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="newsletter title"),
                ),
                ("slug", models.SlugField(unique=True)),
                ("url", models.URLField(blank=True)),
                ("subscribed_url", models.URLField(blank=True)),
                ("unsubscribed_url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "sender_email",
                    models.EmailField(
                        help_text="Sender e-mail", max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "sender_name",
                    models.CharField(
                        help_text="Sender name", max_length=200, verbose_name="sender"
                    ),
                ),
                ("visible", models.BooleanField(default=True, verbose_name="visible")),
                (
                    "already_subscribed_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="fds_mailing.emailtemplate",
                    ),
                ),
                (
                    "confirm_batch_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="fds_mailing.emailtemplate",
                    ),
                ),
                (
                    "confirm_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="fds_mailing.emailtemplate",
                    ),
                ),
                (
                    "default_segment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="fds_newsletter.segment",
                    ),
                ),
            ],
            options={
                "verbose_name": "newsletter",
                "verbose_name_plural": "newsletters",
            },
        ),
        migrations.CreateModel(
            name="NewsletterCMSPlugin",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("fallback", models.BooleanField(default=False)),
                (
                    "newsletter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="fds_newsletter.newsletter",
                    ),
                ),
            ],
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="InSegmentActionConfig",
            fields=[
                (
                    "flowaction_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="flowcontrol.flowaction",
                    ),
                ),
                (
                    "negate",
                    models.BooleanField(
                        default=False,
                        help_text="If not in segment",
                        verbose_name="Negate condition",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fds_newsletter.segment",
                        verbose_name="Segment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("flowcontrol.flowaction",),
        ),
        migrations.CreateModel(
            name="ArchivedSegment",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("fds_newsletter.segment",),
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=100, verbose_name="name"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_index=True,
                        max_length=254,
                        null=True,
                        verbose_name="e-mail",
                    ),
                ),
                ("send_html", models.BooleanField(default=True)),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("last_activation_sent", models.DateTimeField(blank=True, null=True)),
                (
                    "activation_code",
                    models.CharField(
                        default=fragdenstaat_at.fds_newsletter.models.make_activation_code,
                        max_length=40,
                        verbose_name="activation code",
                    ),
                ),
                (
                    "subscribed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="subscribe date"
                    ),
                ),
                (
                    "unsubscribed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="unsubscribe date"
                    ),
                ),
                ("unsubscribe_method", models.CharField(blank=True, max_length=255)),
                ("unsubscribe_reference", models.CharField(blank=True, max_length=255)),
                ("email_hash", models.CharField(blank=True, max_length=64)),
                ("reference", models.CharField(blank=True, max_length=255)),
                ("keyword", models.CharField(blank=True, max_length=255)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "newsletter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscribers",
                        to="fds_newsletter.newsletter",
                        verbose_name="newsletter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "newsletter subscriber",
                "verbose_name_plural": "newsletter subscribers",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="SubscriberImport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=255)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "data_file",
                    models.FileField(
                        help_text="CSV file with 'email' and optional 'name' or 'first_name', 'last_name' and 'tags' columns.",
                        upload_to="newsletter_import",
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=255)),
                ("tags", models.CharField(blank=True, max_length=255)),
                ("new_tags", models.CharField(blank=True, max_length=255)),
                ("data_columns", models.TextField(blank=True)),
                ("email_confirmed", models.BooleanField(default=False)),
                ("started", models.DateTimeField(blank=True, null=True)),
                ("completed", models.DateTimeField(blank=True, null=True)),
                ("row_count", models.IntegerField(blank=True, null=True)),
                ("imported_count", models.IntegerField(blank=True, null=True)),
                (
                    "activation_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fds_mailing.emailtemplate",
                    ),
                ),
                (
                    "newsletter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fds_newsletter.newsletter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscriber Import",
                "verbose_name_plural": "Subscriber Imports",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="HasTagActionConfig",
            fields=[
                (
                    "flowaction_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="flowcontrol.flowaction",
                    ),
                ),
                (
                    "negate",
                    models.BooleanField(
                        default=False,
                        help_text="If doesn't have tag",
                        verbose_name="Negate condition",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fds_newsletter.subscribertag",
                        verbose_name="Subscriber Tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("flowcontrol.flowaction",),
        ),
        migrations.CreateModel(
            name="SubscriberTagActionConfig",
            fields=[
                (
                    "flowaction_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="flowcontrol.flowaction",
                    ),
                ),
                (
                    "remove",
                    models.BooleanField(
                        default=False,
                        help_text="If checked will remove the tag from the subscriber instead of adding it.",
                        verbose_name="Remove tag",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fds_newsletter.subscribertag",
                        verbose_name="Subscriber Tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("flowcontrol.flowaction",),
        ),
        migrations.CreateModel(
            name="SubscribeToNewsletterActionConfig",
            fields=[
                (
                    "flowaction_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="flowcontrol.flowaction",
                    ),
                ),
                ("email_confirmed", models.BooleanField(default=False)),
                ("reference", models.CharField(blank=True, max_length=255)),
                (
                    "newsletter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fds_newsletter.newsletter",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("flowcontrol.flowaction",),
        ),
        migrations.CreateModel(
            name="TaggedSegment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fds_newsletter.segment",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="fds_newsletter.subscribertag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tagged Segment",
                "verbose_name_plural": "Tagged Segments",
            },
        ),
        migrations.AddField(
            model_name="segment",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="fds_newsletter.TaggedSegment",
                to="fds_newsletter.SubscriberTag",
                verbose_name="contains subscribers with all of these",
            ),
        ),
        migrations.CreateModel(
            name="TaggedSubscriber",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fds_newsletter.subscriber",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscribers",
                        to="fds_newsletter.subscribertag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tagged Subscriber",
                "verbose_name_plural": "Tagged Subscribers",
            },
        ),
        migrations.AddField(
            model_name="subscriber",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="fds_newsletter.TaggedSubscriber",
                to="fds_newsletter.SubscriberTag",
                verbose_name="Tags",
            ),
        ),
        migrations.CreateModel(
            name="UnsubscribeFeedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("too_much", "I received too many emails"),
                            (
                                "expected_updates",
                                "I expected more updates regarding certain campaings",
                            ),
                            (
                                "specific_request",
                                "I only signed up regarding a specific FOI request",
                            ),
                            ("not_interested", "The topics are not interesting to me"),
                            ("dislike", "I don't like your work anymore"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Reason",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Comment")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "newsletter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fds_newsletter.newsletter",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fds_newsletter.subscriber",
                    ),
                ),
            ],
            options={
                "verbose_name": "Newsletter Unsubscribe Feedback",
            },
        ),
        migrations.AddConstraint(
            model_name="taggedsubscriber",
            constraint=models.UniqueConstraint(
                fields=("tag", "content_object"), name="unique_tagged_subscriber"
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriber",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("newsletter", "user"),
                name="unique_user_newsletter",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriber",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email__isnull", False)),
                fields=("newsletter", "email"),
                name="unique_email_newsletter",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriber",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("email__isnull", False), ("user__isnull", True)),
                    models.Q(("email__isnull", True), ("user__isnull", False)),
                    models.Q(
                        ("email__isnull", True),
                        ("unsubscribed__isnull", False),
                        ("user__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="newsletter_subscription_user_email",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriber",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("subscribed__isnull", False),
                    ("unsubscribed__isnull", False),
                    _negated=True,
                ),
                name="newsletter_subscription_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="unsubscribefeedback",
            constraint=models.UniqueConstraint(
                fields=("subscriber", "newsletter"), name="unique_feedback_subscriber"
            ),
        ),
    ]
